# Generated by Django 5.0.7 on 2024-08-04 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_id_alter_lesson_id_alter_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
