# Generated by Django 5.0.7 on 2024-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_long_description_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='interactive_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='main_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
