# Generated by Django 5.0.7 on 2024-08-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lesson_interactive_task_lesson_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='raw_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
