# Generated by Django 5.0.7 on 2024-08-12 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lesson_completed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='authorised_users',
            field=models.ManyToManyField(blank=True, related_name='authorised_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
