# Generated by Django 5.0.7 on 2024-08-12 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_authorised_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
