# Generated by Django 5.0.7 on 2024-08-12 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
