# Generated by Django 5.0.7 on 2024-08-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='synthesia_video_id',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
